version: '3.0'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ./src:/opt/client/src:cached
    restart: always